kind: pipeline
type: docker
name: go-ethereum

workspace:
  # IMPORTANT!! - this is where Drone will clone the gloflow repo, and where the gf_builder
  #               container is placing all its code.
  base: /home/gf

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

steps:

  #-------------------------------
  # BUILD_GO
  - name: build_go
    image: glofloworg/gf_builder:latest
    commands:
      - make geth
    when:
      event:
        - push
      branch:
        - master

  #-------------------------------